### ISSUE TITLE
Show the Dockerfile for each released version of the image

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adamcloud#3]
By default, only the last Dockerfile is visible on the Docker Hub Registry. Therefore, if there is 20 image tags released on the Docker Hub, we can only see the Dockerfile for the latest image.

Docker's MySQL and Jenkins image solved this problem in a creative way by adding a "Supported tags and respective Dockerfile links" section. We should create a tag in GitHub whenever we create a tag in Docker Hub, and add a link on the Docker Hub image page to each tagged Dockerfile on github.

**Comment by flangelier** [comment]
Done for snap

**Comment by flangelier** [comment]
Done for adam

**Comment by flangelier** [comment]
Done for hadoop

**Comment by flangelier** [comment]
Done for avocado

**Comment by flangelier** [comment]
Done for spark

**Comment by flangelier** [comment]
Done for scala, only java remaining!!!

**Comment by flangelier** [comment]
Java done
