### ISSUE TITLE
Choose the base Linux/Java distribution for Dockerfile

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adamcloud#5]
## Linux Distribution

Ideally, it would be best to have a single stack of software distribution to reduce the download time and facilitate the maintenability.

We chose Ubuntu 14.04 LTS because it is the most widely used linux distro. If there is strong arguments in favor of another distribution, now would be the good time to discuss it. **Or it is required to support multiple Guest OS?**

_Note: we didn't use the "ubuntu:latest" image, because it adds extra package scripts which did not seem worth the extra size._
## Java Provider and Java Version

Same question for Java. Currently we use Oracle Java 1.7 (latest version).
### OpenJDK vs Oracle JDK

Historically there used to be some issues with OpenJDK and Hadoop - as far as I can remember that was with OpenJDK 1.6. Now perhaps those issues are resolved with OpenJDK 1.7?
- Cloudera still recommends **Oracle JDK 1.6 - 1.8** for CDH5 [using Cloudera Manager](http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cm_ig_cm_requirements.html#concept_tjs_3rg_dk_unique_1), but isn't clear on the JDK provider when [installing with packages](http://www.cloudera.com/content/cloudera/en/documentation/core/latest/topics/cdh_ig_req_supported_versions.html?scroll=concept_pdd_kzf_vp_unique_1).
- HortonWorks [HDP](http://docs.hortonworks.com/HDPDocuments/HDP2/HDP-2.2.0/HDP_Man_Install_v22/index.html#Item1.1) supports both OpenJDK 1.7 and Oracle JDK 1.6-1.7
- [Hadoop wiki](http://wiki.apache.org/hadoop/HadoopJavaVersions) claims to be tested on both OpenJDK 1.7 and Oracle JDK 1.6-1.7.
- Even [MapR](http://doc.mapr.com/display/MapR/Quick+Installation+Guide) seems to have switched to OpenJDK 1.7

Also, I'm not sure if we are violating Oracle's license by distributing Oracle JDK within a docker container.

It seems acceptable to switch to OpenJDK 1.7.
### Java 1.7 vs 1.8

It seems best to stick with java 1.7.

**Comment by flangelier** [comment]
We'll use OpenJDK because we didn't find a way to distribute Oracle JDK in a Docker image by letting the user accept the license.
