### ISSUE TITLE
Choose what the "latest" tag of a docker image should point to

### ISSUE THREAD

**Issue by davidonlaptop** [GELOG/adamcloud#7]
The default tag for docker is "latest" which simplifies the installation for users, as they do not need to specify a tag.

Assuming we have two versions of adam: src and 0.16. **Which should be assigned the "latests" tag?**

it seems best to assign it to the latest released version (not src).

**Comment by flangelier** [comment]
The "latest" tag of an image (e.g. hadoop:latest) will point to the latest released version (e.g. the binary, not the source)
